function [simvect] = mTetrode_diffMtx_plotSimilar(tetstruct,diffmtx,spikenum,distthresh,fs,plotit)
%
% function [simvect] = mTetrode_diffMtx_plotSimilar(tetstruct,diffmtx,spikenum,distthresh,plotit)
%
% plots all spikes that have have distance < distthresh to the spike specified by spikenum
%
% diffmtx is a n x n similarity matrix generated by mTetrode_diffMtx()
%
% tetstruct.times
%          .waveform
%          .peak
%          .trough
%          .width
% measurements in seconds, except width which is in milliseconds. all are scalar except waveform, which is a
% vector
%
% simvect is vector of similar spikes
%


numchannels = 4;

simvect = find(diffmtx(spikenum,:) < distthresh); % distance vector of all spikes to spikenum
if(length(simvect)<2)
   dispstr = ['Distance vector is empty. Try increasing threshold'];
   return
end

wavesize = size(tetstruct(1).waveform);
wavesize = wavesize(2);
timebase = maketimebase(wavesize,fs);

if(plotit)
    figh = figure();
    hold on;
    
    for ploti=1:1:numchannels
        subh = subplot(numchannels,1,ploti);hold on;
        for i=1:1:length(simvect)
            plot(timebase,tetstruct(ploti).waveform(simvect(i),:));
        end
        xlim([0,0.002]);
        hold off;
    end
    tightfig(figh);
end