f=filesep;
if strcmp('\',f);
    disp('Platform = PC');
elseif strcmp('/',f);
    disp('Platform = Unix');

   path('/home/blocks/matlab',path);
   path('/home/msb/matlab/dcp',path);
   path('/home/msb/matlab/sound_utils',path);
   path('/home/msb/matlab/songanal',path);
   path('/home/msb/matlab/songanal/utils',path);
   path('/home/msb/matlab/songanal/xcorr',path);
   path('/home/msb/matlab/songanal/utils/sylanal',path);
   path('/home/msb/matlab/songanal/spect',path);
   path('/home/msb/matlab/utils',path);
   path('/home/msb/matlab/songanal/matprint',path);
   path('/home/msb/matlab/utils/uitools',path);
   path('/home/msb/matlab/cardanal',path);
   path('/home/msb/matlab/noteanal',path);
   path('/home/msb/matlab/foostuff',path);
   path('/home/msb/matlab/altfeed',path);
   path('/home/msb/matlab/altfeed/bird',path);
   path('/home/msb/matlab/altfeed/data',path);
   path('/home/msb/matlab/altfeed/data2',path);
   path('/home/msb/matlab/altfeed/datap26w100',path);
   path('/home/msb/matlab/altfeed/data_b03',path);
   path('/home/msb/matlab/altfeed/data_b05',path);
   path('/home/clint/matlab',path);
   path('/net/pipit/lab_code/uisonganal',path);
   path('/net/pipit/lab_code/uisonganal/spect',path);
   path('/home/msb/matlab',path);
	%path('/home/houde/for_msb/bird',path);
	%path('/home/neal/mlab',path);
	%path('/home/neal/mlab/xfoo',path);
	%path('/home/neal/mlab/xfoo/figures',path);
end
clear f;
