[corrtable_seq1 dattable_seq1] = RA_correlate_pitchvol('singleunits_leq_1pctISI_2pcterr',...
    1,20,50,-40,0,'n','burst',0,10);

[corrtable_seq1_spks dattable_seq1_spks] = RA_correlate_pitchvol('singleunits_leq_1pctISI_2pcterr',...
    1,20,50,-40,0,'n','spikes',0,10);

[corrtable_seq5 dattable_seq5] = RA_correlate_pitchvol('singleunits_leq_1pctISI_2pcterr',...
    5,20,50,-40,0,'n','burst',0,10);

[corrtable_seq5_spks dattable_seq5_spks] = RA_correlate_pitchvol('singleunits_leq_1pctISI_2pcterr',...
    5,20,50,-40,0,'n','spikes',0,10);

save('pitchvol_correlation_analysis','corrtable_seq1','dattable_seq1',...
    'corrtable_seq1_spks','dattable_seq1_spks','corrtable_seq5','dattable_seq5',...
    'corrtable_seq5_spks','dattable_seq5_spks');
